# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(680, 600)
        LoginWindow.setMinimumSize(QtCore.QSize(680, 600))
        LoginWindow.setMaximumSize(QtCore.QSize(680, 600))
        LoginWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.034, y1:0.563, x2:0.982955, y2:0.46, stop:0 rgba(85, 85, 127, 255), stop:1 rgba(0, 85, 127, 255));\n"
"")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        self.label_welcome.setGeometry(QtCore.QRect(150, 90, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(35)
        self.label_welcome.setFont(font)
        self.label_welcome.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username.setGeometry(QtCore.QRect(150, 220, 321, 31))
        self.lineEdit_username.setStyleSheet("QLineEdit {\n"
"border: 2px solid rgb(249, 45, 239);\n"
"border-radius: 15px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(55, 255, 0);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(0, 255, 255);\n"
"}")
        self.lineEdit_username.setText("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(150, 320, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"border: 2px solid rgb(249, 45, 239);\n"
"border-radius: 15px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover{\n"
"border: 2px solid rgb(55, 255, 0);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border: 2px solid rgb(0, 255, 255);\n"
"}")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.signin_btn = QtWidgets.QPushButton(self.centralwidget)
        self.signin_btn.setGeometry(QtCore.QRect(150, 410, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.signin_btn.setFont(font)
        self.signin_btn.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"border-radius: 10px;")
        self.signin_btn.setObjectName("signin_btn")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(150, 370, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_error.setObjectName("label_error")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login"))
        self.label_welcome.setText(_translate("LoginWindow", "<html><head/><body><p>Login</p><p><br/></p></body></html>"))
        self.lineEdit_username.setPlaceholderText(_translate("LoginWindow", "Username"))
        self.lineEdit_password.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.signin_btn.setText(_translate("LoginWindow", "SignIn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
