# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(680, 400)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.shadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.shadowFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(56, 58, 88);\n"
"    \n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 9px;\n"
"}")
        self.shadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shadowFrame.setObjectName("shadowFrame")
        self.label_title = QtWidgets.QLabel(self.shadowFrame)
        self.label_title.setGeometry(QtCore.QRect(20, 50, 621, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_description = QtWidgets.QLabel(self.shadowFrame)
        self.label_description.setGeometry(QtCore.QRect(20, 160, 621, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(96, 150, 200);\n"
"")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.progressBar = QtWidgets.QProgressBar(self.shadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(40, 251, 591, 16))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 5px;\n"
"    text-align:center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"\n"
"    border-radius: 5px;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.608, x2:0.966, y2:0.5, stop:0 rgba(255, 0, 255, 255), stop:1 rgba(85, 170, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_loading = QtWidgets.QLabel(self.shadowFrame)
        self.label_loading.setGeometry(QtCore.QRect(20, 280, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(96, 150, 200);\n"
"")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.label_developer = QtWidgets.QLabel(self.shadowFrame)
        self.label_developer.setGeometry(QtCore.QRect(450, 350, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_developer.setFont(font)
        self.label_developer.setStyleSheet("color: rgb(96, 150, 200);\n"
"")
        self.label_developer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_developer.setObjectName("label_developer")
        self.label_version = QtWidgets.QLabel(self.shadowFrame)
        self.label_version.setGeometry(QtCore.QRect(40, 360, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(96, 150, 200);\n"
"")
        self.label_version.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.label_description_2 = QtWidgets.QLabel(self.shadowFrame)
        self.label_description_2.setGeometry(QtCore.QRect(20, 110, 621, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.label_description_2.setFont(font)
        self.label_description_2.setStyleSheet("color: rgb(96, 150, 200);\n"
"")
        self.label_description_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description_2.setObjectName("label_description_2")
        self.verticalLayout.addWidget(self.shadowFrame)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.label_title.setText(_translate("SplashScreen", "Mirrorlane"))
        self.label_description.setText(_translate("SplashScreen", "<strong>Initializing</strong> database..."))
        self.label_loading.setText(_translate("SplashScreen", "Loading..."))
        self.label_developer.setText(_translate("SplashScreen", "<strong>Created: </strong>Daniel Kibera"))
        self.label_version.setText(_translate("SplashScreen", "v 1.0"))
        self.label_description_2.setText(_translate("SplashScreen", "<html><head/><body><p>Facial Recognition Attendance System</p><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
