# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeWindow(object):
    def setupUi(self, WelcomeWindow):
        WelcomeWindow.setObjectName("WelcomeWindow")
        WelcomeWindow.resize(680, 600)
        WelcomeWindow.setMinimumSize(QtCore.QSize(680, 600))
        WelcomeWindow.setMaximumSize(QtCore.QSize(680, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WelcomeWindow.setWindowIcon(icon)
        WelcomeWindow.setWindowOpacity(1.0)
        WelcomeWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.034, y1:0.563, x2:0.982955, y2:0.46, stop:0 rgba(85, 85, 127, 255), stop:1 rgba(0, 85, 127, 255));")
        self.centralwidget = QtWidgets.QWidget(WelcomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_accounts = QtWidgets.QLabel(self.centralwidget)
        self.label_accounts.setGeometry(QtCore.QRect(170, 210, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_accounts.setFont(font)
        self.label_accounts.setStyleSheet("color: rgb(85, 255, 0);")
        self.label_accounts.setTextFormat(QtCore.Qt.PlainText)
        self.label_accounts.setAlignment(QtCore.Qt.AlignCenter)
        self.label_accounts.setObjectName("label_accounts")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(50, 320, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"border-radius: 10px;\n"
"\n"
"\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        self.label_welcome.setGeometry(QtCore.QRect(170, 110, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(35)
        self.label_welcome.setFont(font)
        self.label_welcome.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.account_btn = QtWidgets.QPushButton(self.centralwidget)
        self.account_btn.setGeometry(QtCore.QRect(380, 320, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.account_btn.setFont(font)
        self.account_btn.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"border-radius: 10px;")
        self.account_btn.setObjectName("account_btn")
        self.label_greeting = QtWidgets.QLabel(self.centralwidget)
        self.label_greeting.setGeometry(QtCore.QRect(140, 30, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(35)
        self.label_greeting.setFont(font)
        self.label_greeting.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_greeting.setAlignment(QtCore.Qt.AlignCenter)
        self.label_greeting.setObjectName("label_greeting")
        WelcomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(WelcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWindow)

    def retranslateUi(self, WelcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWindow.setWindowTitle(_translate("WelcomeWindow", "Welcome- Accounts"))
        self.label_accounts.setText(_translate("WelcomeWindow", "SIGN IN OR CREATE ACCOUNT"))
        self.login_btn.setText(_translate("WelcomeWindow", "Login"))
        self.label_welcome.setText(_translate("WelcomeWindow", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Welcome</span></p></body></html>"))
        self.account_btn.setText(_translate("WelcomeWindow", "Create Account"))
        self.label_greeting.setText(_translate("WelcomeWindow", "<html><head/><body><p><br/></p><p><br/></p><p><br/></p></body></html>"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomeWindow = QtWidgets.QMainWindow()
    ui = Ui_WelcomeWindow()
    ui.setupUi(WelcomeWindow)
    WelcomeWindow.show()
    sys.exit(app.exec_())
